### ISSUE TITLE
Access to Dockerfiles?

### ISSUE THREAD

**Issue by Ramblurr** [cloud66/apps#1]
Any chance you could post the Dockerfiles used to build the images?

In particular I'm interested in the wordpress Dockerfile. I'd like to modify it so it is possible to run multiple WP containers in a stack.

**Comment by khash** [comment]
We are considering that functionality, thank you for the suggestion. However, you can run multiple containers in a stack by editing the services.yml instead of the Docker file (http://help.cloud66.com/building-your-stack/advanced-docker-deployments)

Would that help?

**Comment by foldingbeauty** [comment]
http://help.cloud66.com/building-your-stack/multi-tenancy-for-stacks
